<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Title");
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"doctors-training-center", 
	array(
		"ADD_ELEMENT_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "N",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "N",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "DOKTOR",
			1 => "JOB_DOCKTOR",
			2 => "DATE",
			3 => "CITY",
			4 => "BANNER",
			5 => "PRE_HEADER",
			6 => "BANNER_TEXT",
			7 => "TEXT_BTN",
			8 => "LINK_BTN",
			9 => "TITLE_2",
			10 => "PRE_HEADER_2",
			11 => "TEXT_2",
			12 => "TITLE_3",
			13 => "PRE_HEADER_3",
			14 => "TEXT_3",
			15 => "TEXT_BTN_3",
			16 => "LINK_BTN_3",
			17 => "TITLE_4",
			18 => "PRE_HEADER_4",
			19 => "TEXT_4",
			20 => "TEXT_BTN_4",
			21 => "LINK_BTN_4",
			22 => "PRIMECHANIE",
			23 => "TITLE_5",
			24 => "PRE_HEADER_5",
			25 => "TEXT_5",
			26 => "LIST_PREDSTAVITELSTV",
			27 => "SERTEFICATS",
			28 => "DOCKTORS",
			29 => "VIDEO_YOUTUBE",
			30 => "PRIEMUSHESTVA",
			31 => "GALLERY_TEXT",
			32 => "PRIEMUSHESTVA_2",
			33 => "TITLE_6",
			34 => "TEXT_6",
			35 => "TEXT_BTN_6",
			36 => "LINK_BTN_6",
			37 => "GALLERY_IMAGES",
			38 => "GALLERY_2_IMAGES",
			39 => "IMG",
			40 => "IMG_3",
			41 => "IMG_4",
			42 => "SERTEFICATS",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "N",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "20",
		"IBLOCK_TYPE" => "doctorstrainingcenter",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "NAME",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "DOKTOR",
			1 => "JOB_DOCKTOR",
			2 => "DATE",
			3 => "CITY",
			4 => "",
		),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "6",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "more",
		"PAGER_TITLE" => "Новости",
		"PREVIEW_TRUNCATE_LEN" => "",
		"SEF_MODE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N",
		"COMPONENT_TEMPLATE" => "doctors-training-center",
		"VARIABLE_ALIASES" => array(
			"SECTION_ID" => "SECTION_ID",
			"ELEMENT_ID" => "ELEMENT_ID",
		)
	),
	false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>